version: 2.1

jobs:

    SAST:

        machine: yes

        steps:

          - checkout

          - run: |
               env

               docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest

               docker run --rm --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest env


workflows:

    Scans:

        jobs:

          - SAST

